### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by bb1a2** [mortalis13/HomeDictionary#6]
Thanks a lot for this app. It is great that we have an open-source and unlimited alternative to GoldenDict.

I think the app really needs and deserves some visibility, and the best way to do it is to publish on F-Droid.

Also, the app could be faster. Perhaps you can find ways to optimize it?

**Comment by mortalis13** [comment]
I decided not to make it open source actually, sorry.
Basically I wanted my own customizable app, though GoldenDict is a very good product (and fast), it has its advantages, like support for LSD dictionaries. But for my solution I decided to use just compressed DSL as they are as small as encoded LSD files.
Thanks for your feedback!

**Comment by bb1a2** [comment]
That's unfortunate! It is a great app in any case. I hope to see it continually developed.
